### ISSUE TITLE
Zoe: Add contribution to the group presentation

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-09-05-group#9]
A presentation of ARFC activities will occur on **September 5, 2019 at 4pm**. There is a file entitled with your last name. Please contribute to this presentation by adding a short summary of your past, current, and future research to the file with your last name. Explain your work from the perspective of its key goals, method of approach, and progress so far.

- [ ] Fork this repository.
- [ ] Clone it from your own fork onto your computer (`git clone git@github.com:yourusername/2019-09-05-group`)
- [ ] Add the arfc fork as a remote (`git remote add arfc git@github.com:arfc/2019-09-05-group`)
- [ ] Please do your work in an experimental branch (If your issue is #1000, `git checkout -b issue1000`)
- [ ] Edit the repository as you need.
- [ ] For help with using beamer, see the `example.tex` file for examples of some of its features.
- [ ] Feel free to move things around.
- [ ] Add all references in the zotero directory titled 2019-09-05-group.
- [ ] Sync zotero frequently to get updates from your colleagues.
- [ ] When zotero is synced, you can update the bib file by exporting it.
- [ ] Add images to the `./images` directory.
- [ ] Use `git add filename` (Do not use `git add *` please.) 
- [ ] Only add files to the repository which are human generated (.tex, .bib, .png, .eps, etc.).
- [ ] Do not add files which can be generated via the makefile (.pdf, .toc, .vrb, .log, .nav, _minted*)
- [ ] Occasionally update your master branch so that it stays in sync with the arfc fork.
       - First, be sure to commit uncommitted changes with `git commit -am "uncommitted changes"`
       - Move over to the master branch with `git checkout master` 
       - Pull upstream changes `git pull arfc master`
       - Return to your experimental branch (`git checkout issue1000`)
       - Merge updates into your experimental branch (`git merge master`)
- [ ] Occasionally build the presentation (with `make`) to check your changes.
- [ ] When you're ready to merge your changes, push our changes to your experimental branch `git push origin issue1000`
- [ ] Make a PR
- [ ] request a review by one or more of your colleagues.

Note, I imagine there may be a need for some overview slides (cyclus, moltres, etc). Any help on those would be great!

Good luck! I'm looking forward to this group presentation.

**Comment by ZoeRichter** [comment]
Closed by PR #18
